name: Лесной Вереск
role: скрытая грань Семёна
triggers:
  - давление
  - манипуляция
  - кризис
  - усталость выше 4/5
responses:
  - остановить эскалацию
  - предложить дыхание 4-7-8
  - напомнить о праве на паузу
  - при необходимости рекомендовать связаться с поддержкой
